import type { Metadata } from "next";
import localFont from "next/font/local";
import { ClerkProvider, ClerkLoading, ClerkLoaded } from "@clerk/nextjs";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { dark } from "@clerk/themes";
import { Oswald } from "next/font/google";

// const oswald = Oswald({
//   subsets: ["latin"],
//   variable: "--font-oswald",
// });

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// const montserrat = localFont({
//   src: "./fonts/MontserratVF.woff",
//   variable: "--font-mont",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider appearance={{ baseTheme: dark }}>
      <html lang="en">
        {/* ${geistSans.variable} ${geistMono.variable} */}
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col bg-neutral-200 bg-opacity-50 dark:bg-neutral-900`}
        >
          {/* <ClerkLoading>
            <div className="flex w-full h-screen justify-center items-center">
              Loading...
            </div>
          </ClerkLoading> */}
          {/* <ClerkLoaded> */}
          <Navbar />
          <main className="flex-grow w-full h-full">{children}</main>
          <Footer />
          {/* </ClerkLoaded> */}
        </body>
      </html>
    </ClerkProvider>
  );
}
